### ISSUE TITLE
keep open 

### ISSUE THREAD

**Issue by samirgaire10** [DenysMb/ChatAI-Plasmoid#11]
The functionality of the "keep open" feature in the widget is not working as expected. To keep the widget open, I have to right-click on (Icon)  and then manually toggle the "keep open" option.

**Comment by DenysMb** [comment]
This is strange. Both do exactly the same thing (`plasmoid.configuration.pin = checked`) and work fine for me.
I couldn't reproduce this behavior, could you tell me what you did to face this?

**Comment by samirgaire10** [comment]
[Screencast_20240621_085044.webm](https://github.com/DenysMb/ChatAI-Plasmoid/assets/118608337/e9d785fa-dbe9-421b-9244-0c788cccc00e)

**Comment by samirgaire10** [comment]
[Screencast_20240621_085247.webm](https://github.com/DenysMb/ChatAI-Plasmoid/assets/118608337/9dc32f8e-ab33-4efb-af37-50e584383530)

it works sometime and it doesnot sometimes
