### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by hazel-bunny** [DenysMb/ChatAI-Plasmoid#13]
This plasmoid (assuming it is free and open source) needs to have a license for the sake of redistribution. Could you kindly add one?

I know that the plasmoid does not include any models, but make sure that the license does not conflict with the AI models that can be accessed by this plasmoid. A BSD-style license may be better, I guess.

**Comment by DenysMb** [comment]
Done. https://github.com/DenysMb/ChatAI-Plasmoid/commit/6918d329efb3222525c538342c1829b0a96d490a
