### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by type0dev** [DenysMb/ChatAI-Plasmoid#14]
great project, can you add dark mode and a way to pick local llm such as koboldcpp or ollama

**Comment by DenysMb** [comment]
Thank you.

Since this widget is basically a WebEngine, I don't think we can use local LLM.

But, I  am planning to create a new widget to be used with Ollama.
I worked in a [widget](https://github.com/DenysMb/ChatQTP-Plasmoid) in the past that I can use as a base for the new widget.

**Comment by DenysMb** [comment]
You can use this widget to use local models: https://github.com/DenysMb/ChatQT-Plasmoid
