### ISSUE TITLE
Option to use own proxy to access models

### ISSUE THREAD

**Issue by Blacksuan19** [DenysMb/ChatAI-Plasmoid#16]
As the title says, I want the option to use my own proxy to access chatGPT and other models, simply add something like https://lobechat.com/chat or https://get.big-agi.com/ as a model option that way anyone can use their own proxy and credentials with them.

**Comment by DenysMb** [comment]
Hey!
Sure. I'll add them.
Expect this to be ready tomorrow.

I will work on a way to let users add any model from the config too, I was working on it but I had to stop for some days.

**Comment by Blacksuan19** [comment]
That's perfect, thanks!

**Comment by DenysMb** [comment]
Added both in the 1.7.0 release.
