### ISSUE TITLE
Bug: Can't sign into OpenAI with Google account

### ISSUE THREAD

**Issue by joobert** [DenysMb/ChatAI-Plasmoid#2]
This may be out of your control, but I currently cannot sign in to ChatGPT using my Google account with this plasmoid due to the browser it uses being "untrusted"

![image](https://github.com/DenysMb/ChatAI-Plasmoid/assets/73461741/90f93743-f163-40ae-9a58-e175e0431775)

**Comment by DenysMb** [comment]
I will have a look on this. Maybe there is an option or something like that for WebEngineView that I can use to fix this.
