### ISSUE TITLE
Session loses on restart and copy from chatgpt not working.

### ISSUE THREAD

**Issue by murapa96** [DenysMb/ChatAI-Plasmoid#24]
Hi! I think i have a configuration problem, but anytime I reboot my computer, I need to login again on any chatbot. Also, the button to copy feature doesn't work.

I'm using Kde Plasma 6 + Wayland

**Comment by kevinbburns** [comment]
@murapa96  It's an easy fix if you want to do it before DenysMB can fix it, or I can create a fork. If you

Open up a terminal, probably Konsole.

cd ~/.local/share/plasma/plasmoids/ChatAI-Plasmoid/contents/ui

You can use either nano, vim or an editor of your choice, open up WebView.qml. Go down to the WebEngineProfile section, look for offTheRecord and storagename, you need to swap the lines to this:

offTheRecord: false
storageName: "chat-ai"

After that, the session and cache start saving again, it was a recent change in Qt on the profiling.

**Comment by murapa96** [comment]
I tried that solution, but i have the file like that. I think I have something broke on my system. The "copy" feature on chatgpt doesn't work either.

**Comment by crazy-matt** [comment]
Hello @kevinbburns,

I got the exact same issues, both.
I've checked the file mentioned and got already the right values. I installed the widget this Sunday only.

```bash
❯ sed -n '/WebEngineProfile/,+10p' ~/.local/share/plasma/plasmoids/ChatAI-Plasmoid/contents/ui/WebView.qml
WebEngineProfile {
id: webProfile
httpUserAgent: getUserAgent()
storageName: "chat-ai"
offTheRecord: false
httpCacheType: WebEngineProfile.DiskHttpCache
persistentCookiesPolicy: WebEngineProfile.ForcePersistentCookies
}

profile: webProfile


```

Is there any other quick fix I could apply?

**Comment by DenysMb** [comment]
Hey!

I will take a look at it this weekend when I get back home.
I have been on vacation, visiting family since the beginning of this month, so I couldn't take a look at it earlier.

**Comment by murapa96** [comment]
I really love your plasmoid. It's a very powerful tool, and love that it's open source.  Thank you for your support. I'm sharing with all my friends.

**Comment by l3ifk** [comment]
I encounter the same issues. The file already contained the described lines. I'm using Arch + Plasma (Wayland)

**Comment by OlegAckbar** [comment]
As of Qt 6.8.1 I can no longer experience the issue. Can anyone else confirm?

**Comment by l3ifk** [comment]
> As of Qt 6.8.1 I can no longer experience the issue. Can anyone else confirm?

Same for me. Works now as intended

**Comment by murapa96** [comment]
All the issues are fixed. Thank you dev!
