### ISSUE TITLE
Bug in v1.3.1 - missing icons settings in Appearance

### ISSUE THREAD

**Issue by JustDj-Git** [DenysMb/ChatAI-Plasmoid#7]
Missing icon settings in General

![Screenshot_20240611_102856](https://github.com/DenysMb/ChatAI-Plasmoid/assets/3286315/75d4409b-77f1-4137-942a-7a83cfd6e6f2)

**Comment by DenysMb** [comment]
Hey!

Thank you for this.
It was my mistake. I just fixed: https://github.com/DenysMb/ChatAI-Plasmoid/releases/tag/1.3.2

With `plasmoidviewer` not working I need to do changes locally in `$HOME/.local/share/plasma/plasmoids/ChatAI-Plasmoid` and, after test, I copy the code to my local project and push the changes. Doing this I pushed the changes from ConfigGeneral to ConfigAppearance without realize.

Now I just did a link between both folder until the problem with `plasmoidviewer` got fixed.
