### ISSUE TITLE
Displays blurry when scaled to non-integer factors, displays clearly when scaled to integer factors.

### ISSUE THREAD

**Issue by CatOS-Home** [DenysMb/ChatAI-Plasmoid#9]
It's a really great plasmoid!That's a really great idea, but I'm running into this annoying problem.

200% scale factor:
![图片](https://github.com/DenysMb/ChatAI-Plasmoid/assets/151033726/7268cb9b-798d-4a93-8af4-d8ee890a02ae)

150% scale factor:
![图片](https://github.com/DenysMb/ChatAI-Plasmoid/assets/151033726/6d311959-21a4-497d-b427-5d3ced0c05d5)

**Comment by DenysMb** [comment]
When you talk about scale factor, do you mean the `Global scale` in `System Settings > Display Configuration`?
Can you confirm if you have the same issue using the Plasma `Web Browser` widget and going to `https://duckduckgo.com/cha`t?

![image](https://github.com/DenysMb/ChatAI-Plasmoid/assets/33737137/b791c2ae-a9a5-4750-9dc4-024e993fc6ec)

The `Web Browser` widget have some scaling configuration that I can use if it fixes your problem.

**Comment by CatOS-Home** [comment]
Thanks for your reply.
Yes,I mean  the `Global scale` in `System Settings > Display Configuration`.
The Plasma `Web Browser` widget has the same problem.

My opera system is `archlinux based system`.
This is my other running environment:
![图片](https://github.com/DenysMb/ChatAI-Plasmoid/assets/151033726/629b9a4a-95ab-458b-b69c-e462971f3a53)


> When you talk about scale factor, do you mean the `Global scale` in `System Settings > Display Configuration`? Can you confirm if you have the same issue using the Plasma `Web Browser` widget and going to `https://duckduckgo.com/cha`t?
> 
> ![image](https://private-user-images.githubusercontent.com/33737137/338699943-b791c2ae-a9a5-4750-9dc4-024e993fc6ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxNTQ0MzcsIm5iZiI6MTcxODE1NDEzNywicGF0aCI6Ii8zMzczNzEzNy8zMzg2OTk5NDMtYjc5MWMyYWUtYTlhNS00NzUwLTlkYzQtMDI0ZTk5M2ZjNmVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDAxMDIxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmNWY5OTIwMjM0OGZlOTgzOTBkOTY1ZTRjNDhhYTE2ZjJkOTc5ZjM0MjZjNDYxZmE4MGIyMTRhMjI2MDQ0OTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zKEnSkroDiOAWGbqkD-o-nHxKxeuoU4r0SYBL49mYKw)
> 
> The `Web Browser` widget have some scaling configuration that I can use if it fixes your problem.

**Comment by DenysMb** [comment]
If the `Web Browser` widget has the same problem, it will be difficult to know what is causing this, but I'll have a look.
Changing the scaling options in the configuration of the `Web Browser` didn't change anything?

**Comment by CatOS-Home** [comment]
> If the `Web Browser` widget has the same problem, it will be difficult to know what is causing this, but I'll have a look. Changing the scaling options in the configuration of the `Web Browser` didn't change anything?

No,Changing the scaling options  didn't solve the problem.

**Comment by Cherkah** [comment]
i'm facing to th esame issue:
2 screen withe globale system resolution : 1920 x 1080

laptop hdpi 125% =>

![screenshot_27 09 24_16h13](https://github.com/user-attachments/assets/daae47dc-0e94-4920-bac9-8161a60eb9ca)

**Comment by OlegAckbar** [comment]
This is no longer an issue with Qt 6.8 and KDE Frameworks 6.7

**Comment by DenysMb** [comment]
> This is no longer an issue with Qt 6.8 and KDE Frameworks 6.7

I am glad to know.

In this case, I'll close the issue.
